name: gdpr_admob
description: A Flutter package to manage GDPR consent for AdMob ads in the European Economic Area (EEA) and initialize Google Mobile Ads SDK based on user consent status in Flutter applications.
version: 1.0.3
homepage: https://github.com/Abdullah-Youssef/gdpr_admob.git

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
